name: 'cross repo dispatch'
description: 'Run a GHAction workflow in a different repository and get the output status'
inputs:
  owner:
    description: 'target repo owner'
    required: true
  repo:
    description: 'target repo'
    required: true
  ref:
    description: 'ref of target repo to use'
    required: true
  pat:
    description: 'target repo personal access token'
    required: true
  user:
    description: 'target repo user'
    required: true
  sha:
    description: 'unique step name "sha" to search for in jobs'
    required: true
  client_payload:
    description: 'data to send to the workflow'
    required: false
  workflow_status_retry_interval:
    description: 'interval to retry getting workflow status'
    required: false
    default: 10
  workflow_status_timeout:
    description: 'timeout to fail getting workflow status'
    required: false
    default: 600
  max_runs:
    description: 'max number of runs (starting at most recent) back to check for matching step "name"'
    required: false
    default: 10
  event_type:
    description: 'event type label'
    required: true
outputs:
  status:
    description: 'workflow status'
  html_url:
    description: 'html url of workflow'
runs:
  using: docker
  image: Dockerfile